vkanban/Auth/urls.py
from django.urls import path

from . import views
app_name = "Auth"

urlpatterns = [
        path("login/",views.Login,name = "login"),
        path("registration/",views.registration,name = "register"),
        path("logout/",views.logout_view,name = "logout")
        ]

vkanban/kanban/urls.py
from django.urls import path

from . import views
app_name = "kanban"

urlpatterns = [
        path("home/",views.home,name = "home"),
        path("kontent/<int:id>/", views.kontent, name = "kontent"),
        path("create_board/", views.create_board, name = "create_board"),
        path("add_card/<int:kid>/<str:state>/",views.add_card, name = "add_card"),
        path("delete_card/<int:kid>/<int:cid>/",views.delete_card, name = "delete_card"),
        path("join_board/", views.join_board, name = "join_board"),
        path("move_card/<int:kid>/<int:cid>/<str:state>/", views.move_card, name = "move_card"),
        # path("registration/",views.registration,name = "register")
        ]

vkanban/vkanban/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Auth.urls")),
    path('/', include("kanban.urls")),
]

vkanban/kanban/models.py
from django.db import models
from django.contrib.auth.models import User


class Kanban(models.Model):
    description = models.CharField(max_length=1000)
    KanbanName = models.CharField(max_length=200)
    KanbanId = models.IntegerField(unique=True, primary_key=True)


class Cards(models.Model):

    cardID = models.IntegerField()
    KanbanId = models.ForeignKey(Kanban, on_delete=models.PROTECT)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    state = models.TextField(max_length=200)
    last_edit = models.DateTimeField()
    content = models.TextField(max_length=1000)
    deadline = models.DateField(null=True, blank=True)
    class Meta:
        unique_together = (('cardID', 'KanbanId'))

# class creates(models.Model):
#     card = models.ForeignKey(Cards, on_delete=models.PROTECT)
#     KanbanId = models.ForeignKey(Kanban, on_delete=models.PROTECT)
#     user = models.ForeignKey(User, on_delete=models.PROTECT)

class hasAcessTo(models.Model):
    kanban = models.ForeignKey(Kanban, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

# class contains(models.Model):

vkanban/kanban/forms.py
from django import forms
from django.forms import ModelForm
from kanban.models import *

class creatBoardForm(ModelForm):
    class Meta:
        model = Kanban
        fields = ['KanbanId','KanbanName','description']
        
class addCardForm(ModelForm):
    class Meta:
        model = Cards
        fields = ['cardID','content', 'deadline']

class joinBoardForm(forms.Form):
    kanbanId = forms.IntegerField()

vkanban/kanban/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from kanban.models import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from kanban.forms import *
from django.http import HttpResponse
from django.db.utils import IntegrityError
# Create your views here.
@login_required
def home(request):
    # breakpoint()
    if(request.method == "GET"):
        boards = hasAcessTo.objects.filter(user = request.user)
        context = []
        for i  in boards:
            d = dict()
            d['id'] = i.kanban.KanbanId
            d['name'] = i.kanban.KanbanName
            d['description'] = i.kanban.description
            context.append(d)
        return render(request, 'kanban/boards.html', {'boards':context})
    else:
        return None

@login_required
def kontent(request, id):
    if(request.method == "GET"):
        # breakpoint()
        cards = Cards.objects.filter(KanbanId=id)
        name = Kanban.objects.get(pk=id).KanbanName
        states = ['todo', 'done','inprogress','onhold']
        todo = []
        inprogress = []
        done = []
        onhold = []
        for i in cards:
            d = dict()
            d['author'] = i.author.username
            d['content'] = i.content
            d['deadline'] = i.deadline
            d['state'] = i.state
            d['cardID'] = i.cardID
            d['last_edit'] = i.last_edit
            if(i.state=="todo"):
                todo.append(d)
            elif(i.state=="in_progress"):
                inprogress.append(d)
            elif(i.state=="done"):
                done.append(d)
            elif(i.state=="on_hold"):
                onhold.append(d)

        return render(request,'kanban/cards.html', {'todo':todo, 'in_progress':inprogress, 'done':done,'on_hold':onhold,'name':name, 'kid':id})

@login_required
def create_board(request):
    if request.method == 'GET':
        form = creatBoardForm()
        return render(request, 'kanban/create_board.html',{'form':form})
    else:
        form = creatBoardForm(request.POST)
        if form.is_valid():
            new_board = Kanban()
            new_board.KanbanId = form.cleaned_data['KanbanId']
            new_board.KanbanName = form.cleaned_data['KanbanName']
            new_board.description = form.cleaned_data['description']
            new_board.save()
            acess = hasAcessTo()
            acess.kanban = new_board
            acess.user = request.user
            acess.save()
            return redirect('kanban:home')
        else:
            return render(request, 'kanban/create_board.html', {'form': form})
    
@login_required
def add_card(request, kid, state):
    if request.method == 'GET':
        form = addCardForm()
        return render(request, 'kanban/add_card.html', {'form':form, 'error':""})
    else:
        form = addCardForm(request.POST)
        if form.is_valid():
            new_card = Cards()
            new_card.KanbanId = Kanban.objects.get(pk=kid)
            new_card.author = request.user
            new_card.cardID = form.cleaned_data['cardID']
            new_card.state = state
            new_card.last_edit = datetime.now()
            new_card.content = form.cleaned_data['content']
            new_card.deadline = form.cleaned_data['deadline']
            try:
                new_card.save()
                # created = creates()
                # created.card = new_card
                # created.KanbanId = Kanban.objects.get(pk=kid)
                # created.user = request.user
                # created.save()
                return redirect('kanban:kontent', id=kid)
            except IntegrityError:
                return render(request, 'kanban/add_card.html', {'form':form, 'error':"Card with this ID already exists, try a different ID"})    
        else:
            return render(request, 'kanban/add_card.html', {'form':form, 'error':""})

@login_required
def delete_card(request,kid,cid):
    Cards.objects.filter(KanbanId=kid).filter(cardID=cid).delete()
    return kontent(request, kid)

@login_required
def join_board(request):
    if request.method == 'GET':
        form = joinBoardForm()
        return render(request, 'kanban/join_board.html', {'form':form})
    else:
        form = joinBoardForm(request.POST)
        if form.is_valid():
            access = hasAcessTo()
            access.kanban = Kanban.objects.get(pk=form.cleaned_data['kanbanId'])
            access.user = request.user
            access.save()
            return redirect('kanban:home')
        else:
            return render(request, 'kanban/join_board.html', {'form':form})

@login_required
def move_card(request, kid, cid, state):
    card_objs = Cards.objects.filter(KanbanId=kid).filter(cardID=cid)
    card = card_objs[0]
    new_card = Cards()
    new_card.cardID = card.cardID
    new_card.KanbanId = card.KanbanId
    new_card.state = state
    new_card.author = request.user
    new_card.last_edit = datetime.now()
    new_card.deadline = card.deadline
    new_card.content = card.content
    card.delete()
    new_card.save()
    return redirect('kanban:kontent', id=kid)

vkanban/kanban/templates/kanban/add_card.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Card</title>
</head>
<body>
    {{error}}
    <form  method="post" novalidate class="formDiv" id="form">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit" name="login">submit</button>
        </form>
</body>
</html>

vkanban/kanban/templates/kanban/boards.html
<!doctype html>
<html lang="en">
  <head>
    <script>
        openboard()
    </script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>VKanban | Organized Projects</title>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }
      .btn1
        {
            border: none;
            outline: none;
            height: 50px;
            width: 60%;
            background-color: black;
            color: white;
            border-radius: 4px;
            font-weight:bold ;

        }
        .btn1:hover
        {
            background: white;
            border: 1px solid;
            color: black;
        }
        .btn2
        {
            border: none;
            outline: none;
            height: 40px;
            width: 80%;
            background-color: black;
            color: white;
            border-radius: 4px;
            font-weight:bold ;

        }
        .btn2:hover
        {
            background: white;
            border: 1px solid;
            color: black;
        }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
      .link1 {
        color: white;
      }
      .link1:hover {
        color: black;
      }
    </style>

    
  </head>
  <body>
    
<header>

  <div class="navbar navbar-dark bg-black shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>VKanban</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>





<main>
<div class="bg-image bg-opacity-25"
style="background-image:url('image.png');"
>
<div class="mask" style="background-color: rgba(33, 33, 33, 0.8);">
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light" style="color: white;">Kanban Projects</h1>
        <p class="lead text"style="color: rgb(200,200,200);">Access your kanban boards here.</p>
        <p>
          <div class="row-col">

          <div class="col">
          <button type="submit" class="btn1 mt-3 " onclick="location.href='{% url 'kanban:create_board'%}'">Create a Kanban</button>
        </div>
        <div class="col">
          <button type="submit" class="btn1 mt-3 mb-4" onclick="location.href='{% url 'kanban:join_board'%}'">Join a Kanban</button>
        </div>
        </div>
        </p>
      </div>
    </div>
  </div>
  </div>
  </section>

<!-- ================================================================================= -->

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for i in boards %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <h4>{{i.name}}</h4>
              <p class="card-text">{{i.description}}</p>
              <div class="d-flex justify-content-center ">
                  <!-- <button type="button" class="btn2 " onclick="openboard()">Open</button> <a href="{% url 'kanban:kontent' id=i.id %}" class="link1">Open</a>-->
                  <button type="submit" class="btn2" onclick="location.href='{% url 'kanban:kontent' id=i.id %}'">Open</button>
                </div>
              </div>
              </div>
            {% endfor %}
            </div>

            



          </div>
        </div>
      </div>
<!--===========================================================================================--> -->
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1"></p>
    <p class="mb-0">Want to log out? <a href="{% url 'Auth:logout' %}">Log Out</a> </p>
  </div>
</footer>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      
  </body>
</html>

vkanban/kanban/templates/kanban/create_board.html
<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>VKanban | Create Board</title>
    <style>
        *{
                padding: 0;
                margin: 0;
                box-sizing: border-box;
            }
        
        body
        {
            background : rgb(219, 226, 226)
        }
        .row
        {
            background: white;
            border-radius: 30px;
            box-shadow: 12px 12px 22px grey;
        }
        img{
            border-radius: 30px;
          

        }
        .btn1
        {
            border: none;
            outline: none;
            height: 50px;
            width: 100%;
            background-color: black;
            color: white;
            border-radius: 4px;
            font-weight:bold ;

        }
        .btn1:hover
        {
            background: white;
            border: 1px solid;
            color: black;
        }
    </style>
  </head>
  <body>
    <section class ="Form my-4 mx-5">
    <div class="container w-50">
        <div class ="row g-0">
                <h1 class = "font-weight-bold px-5 pt-5 d-flex justify-content-center">Create Board</h1>
                <form class = "px-4 py-5" method = "post" action = "">
                <div class="col-lg-3 py-5 mx-auto ">

                    <form  method="post" novalidate class="formDiv" id="form">
                    {%csrf_token%}
                    {{form.as_p}}
                </div> 
                <div class="col-lg-3 py-2 mx-auto">
                    
                    <button type="submit" class="btn1 mt-3 mb-4 "name="login">Create</button>
                 
            </div>

            </div>  


                    
                    </form>

    </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

vkanban/kanban/templates/kanban/join_board.html
<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>VKanban | Join Board</title>
    <style>
        *{
                padding: 0;
                margin: 0;
                box-sizing: border-box;
            }
        
        body
        {
            background : rgb(219, 226, 226)
        }
        .row
        {
            background: white;
            border-radius: 30px;
            box-shadow: 12px 12px 22px grey;
        }
        img{
            border-radius: 30px;
          

        }
        .btn1
        {
            border: none;
            outline: none;
            height: 50px;
            width: 100%;
            background-color: black;
            color: white;
            border-radius: 4px;
            font-weight:bold ;

        }
        .btn1:hover
        {
            background: white;
            border: 1px solid;
            color: black;
        }
    </style>
  </head>
  <body>
    <section class ="Form my-4 mx-5">
    <div class="container w-50" >
        <div class ="row g-0 ">
                <h1 class = "font-weight-bold px-5 pt-5 d-flex justify-content-center">Join Board</h1>
                <form class = "px-4 py-5" method = "post" action = "">
                <div class="col-lg-3 py-5 mx-auto">

                    <form  method="post" novalidate class="formDiv" id="form">
                        {%csrf_token%}
                        {{form.as_p}}
                       
                        
                </div> 
                <div class="col-lg-3 py-2 mx-auto">
                    
                    <button type="submit" class="btn1 mt-3 mb-4 " name="login">Join</button>
                    
            </div>

            </div>  


                    
                    </form>

    </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

vkanban/kanban/templates/kanban/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cards</title>
</head>
<body>
</body>
</html>